# Generated by Django 2.0.2 on 2018-03-04 15:08

from django.db import migrations, models
import django.db.models.deletion
import messageboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.UUIDField(default=messageboard.models.uuid_default, editable=False, primary_key=True, serialize=False)),
                ('messageTitle', models.CharField(max_length=200)),
                ('messageContent', models.TextField(max_length=5000)),
                ('messageDateTime', models.DateTimeField(auto_now=True)),
                ('messageRead', models.IntegerField(default=0)),
                ('messageComment', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.UUIDField(default=messageboard.models.uuid_default, editable=False, primary_key=True, serialize=False)),
                ('userName', models.CharField(default=messageboard.models.userName_default, max_length=30)),
                ('userGender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10)),
                ('userAge', models.IntegerField(blank=True, null=True)),
                ('userEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('userIcon', models.URLField(blank=True, null=True)),
                ('userPassword', models.CharField(default=messageboard.models.password_default, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messageboard.User'),
        ),
    ]
